# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1595afa696f559f92a19da3185b6fbf7ac260c32dde4b3e12f24fc3bacd147914f48f9706a7cf4ef5ec71f9db14d4b6ebbbbcdf2c371ea92916019552057a68

test:
  secret_key_base: b004fb49fbe620b4e47d395bffc342e6df62af3ab5fa38c7969b4e00b6e147c1d59a40c15eeda262c17fbf23003ffe91ac55cee8bd643a5f6c0dd13435718e4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
